//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.19 at 07:25:21 ���� CST 
//


package com.houseOnline.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="base" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="debug" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{}robot" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}support" minOccurs="0"/>
 *         &lt;element ref="{}mongoServer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="mongoDBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phantomjsPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ip",
    "code",
    "base",
    "debug",
    "robot",
    "support",
    "mongoServer",
    "mongoDBName",
    "dataPath",
    "phantomjsPath"
})
@XmlRootElement(name = "application")
public class Application {

    protected String ip;
    protected Integer code;
    protected String base;
    protected Boolean debug;
    protected List<Robot> robot;
    protected Support support;
    protected List<MongoServer> mongoServer;
    protected String mongoDBName;
    protected String dataPath;
    protected String phantomjsPath;

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIp() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIp(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCode(Integer value) {
        this.code = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the debug property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDebug() {
        return debug;
    }

    /**
     * Sets the value of the debug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDebug(Boolean value) {
        this.debug = value;
    }

    /**
     * Gets the value of the robot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the robot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRobot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Robot }
     * 
     * 
     */
    public List<Robot> getRobot() {
        if (robot == null) {
            robot = new ArrayList<Robot>();
        }
        return this.robot;
    }

    /**
     * Gets the value of the support property.
     * 
     * @return
     *     possible object is
     *     {@link Support }
     *     
     */
    public Support getSupport() {
        return support;
    }

    /**
     * Sets the value of the support property.
     * 
     * @param value
     *     allowed object is
     *     {@link Support }
     *     
     */
    public void setSupport(Support value) {
        this.support = value;
    }

    /**
     * Gets the value of the mongoServer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mongoServer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMongoServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MongoServer }
     * 
     * 
     */
    public List<MongoServer> getMongoServer() {
        if (mongoServer == null) {
            mongoServer = new ArrayList<MongoServer>();
        }
        return this.mongoServer;
    }

    /**
     * Gets the value of the mongoDBName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMongoDBName() {
        return mongoDBName;
    }

    /**
     * Sets the value of the mongoDBName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMongoDBName(String value) {
        this.mongoDBName = value;
    }

    /**
     * Gets the value of the dataPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataPath() {
        return dataPath;
    }

    /**
     * Sets the value of the dataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPath(String value) {
        this.dataPath = value;
    }

    /**
     * Gets the value of the phantomjsPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhantomjsPath() {
        return phantomjsPath;
    }

    /**
     * Sets the value of the phantomjsPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhantomjsPath(String value) {
        this.phantomjsPath = value;
    }

    /**
     * Method getMongoServerCount.
     * 
     * @return the size of this collection
     */
    public int getMongoServerCount(
    ) {
        return this.mongoServer.size();
    }
}
